hostname: "figport.dev.minsky.cc"
figport:
  prefix: "figport"
  globalsecret: ""
figma:
  # oauthbase: ""
  # clientid: ""
  # clientsecret: ""
  # redirecturi: ""
  token: ""

s3:
  endpoint: 127.0.0.1:9000
  accesskey: "minioadmin"
  secretkey: "minioadmin"
  usessl: false
  region: us-east-1
  bucket: figport

redis:
  address: "localhost:6379"
