hostname: "figport.dev.minsky.cc"
figport:
  debug: true
  prefix: "figport"

figma:
  oauthbase: ""
  clientid: ""
  clientsecret: ""
  redirecturi: ""

s3:
  endpoint: "http://192.168.8.135:9000"
  accesskey: "minioadmin"
  secretkey: "minioadmin"
  usessl: false
  region: us-east-1
  bucket: figport

redis:
  address: "localhost:6379"
